#!/bin/sh
#killall -9 imagent &> /dev/null
#killall -9 identityservicesd &> /dev/null
launchctl unload /System/Library/LaunchDaemons/com.apple.imagent.plist
launchctl load /System/Library/LaunchDaemons/com.apple.imagent.plist
launchctl unload /System/Library/LaunchDaemons/com.apple.identityservicesd.plist
launchctl load /System/Library/LaunchDaemons/com.apple.identityservicesd.plist
exit 0;
